caldera_cycleways_frontpage:
    path:     /
    defaults: { _controller: CalderaCyclewaysBundle:Frontpage:index }

caldera_cycleways_incident_streetview_check:
    path:     /streetviewcheck
    defaults: { _controller: CalderaCyclewaysBundle:Incident:googleMapsCoord }
    options:
        expose: true

caldera_cycleways_incident_show:
    path:     /show/{slug}
    defaults: { _controller: CalderaCyclewaysBundle:Incident:show }
    options:
        expose: true
        
caldera_cycleways_incident_source:
    path:     /incidents
    defaults: { _controller: CalderaCyclewaysBundle:Incident:load }
    options:
        expose: true

caldera_cycleways_incident_list_city:
    path:     /{citySlug}/list
    defaults: { _controller: CalderaCyclewaysBundle:Incident:list }

caldera_cycleways_incident_map_city:
    path:     /{citySlug}
    defaults: { _controller: CalderaCyclewaysBundle:Incident:map }

caldera_cycleways_incident_add:
    path:     /{citySlug}/addincident
    defaults: { _controller: CalderaCyclewaysBundle:Incident:add }

caldera_cycleways_incident_comment_add:
    path:     /{slug}/addcomment
    defaults: { _controller: CalderaCyclewaysBundle:Post:write }