caldera_cycleways_incident_map:
    path:     /
    defaults: { _controller: CalderaCyclewaysBundle:Incident:map }

caldera_cycleways_incident_source:
    path:     /incidents
    defaults: { _controller: CalderaCyclewaysBundle:Incident:load }
    options:
        expose: true

caldera_cycleways_incident_map_city:
    path:     /{citySlug}
    defaults: { _controller: CalderaCyclewaysBundle:Incident:map }