caldera_cycleways_city:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/city.yml"
    prefix: /

caldera_cycleways_incident:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/incident.yml"
    prefix: /

caldera_cycleways_interal:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/internal.yml"
    prefix: /