services:
    caldera.cycleways.permalink_manager.sqibe:
        class: Caldera\Bundle\CyclewaysBundle\PermalinkManager\SqibePermalinkManager
        arguments: [ '@router', '%sqibe.api_url%', '%sqibe.api_username%', '%sqibe.api_password%' ]

    caldera.cycleways.manager.incident_manager:
        class: Caldera\Bundle\CyclewaysBundle\Manager\IncidentManager\IncidentManager
        arguments: ['@doctrine', '@fos_elastica.manager']

    caldera.cycleways.manager.post_manager:
        class: Caldera\Bundle\CyclewaysBundle\Manager\PostManager\PostManager
        arguments: ['@doctrine']

    caldera.view_storage.cache:
        class: Caldera\Bundle\CyclewaysBundle\ViewStorage\ViewStorageCache
        arguments: ['@doctrine.cache.memcached', '@security.token_storage']

    caldera.view_storage.persister:
        class: Caldera\Bundle\CyclewaysBundle\ViewStorage\ViewStoragePersister
        arguments: ['@doctrine.cache.memcached', '@doctrine']

    caldera.parser.multistep:
        class: Caldera\Bundle\CyclewaysBundle\Parser\MultiStepParser\MultiStepParser
        calls:
            - [ addStep, [ '@caldera.parser.multistep.link' ]]
            - [ addStep, [ '@caldera.parser.multistep.markdown' ]]
            - [ addStep, [ '@caldera.parser.multistep.anchor' ]]

    caldera.parser.multistep.markdown:
        class: Caldera\Bundle\CyclewaysBundle\Parser\MultiStepParser\Step\MarkdownParserStep
        arguments: [ '@markdown.parser' ]

    caldera.parser.multistep.link:
        class: Caldera\Bundle\CyclewaysBundle\Parser\MultiStepParser\Step\LinkParserStep

    caldera.parser.multistep.anchor:
        class: Caldera\Bundle\CyclewaysBundle\Parser\MultiStepParser\Step\AnchorParserStep

    caldera_criticalmass.twig.extension:
        class: Caldera\Bundle\CyclewaysBundle\Twig\Extension\TwigParseExtension
        arguments:
            - '@caldera.parser.multistep'
        tags:
            - { name: twig.extension }
