fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        criticalmass:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                incident:
                    mappings:
                        id: ~
                        title: ~
                        description: ~
                        city: { type: string, index: not_analyzed }
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\Incident
                        provider: ~
                        listener: ~
                        finder: ~
                    indexable_callback: 'indexable'