framework:
    translator:      { fallback: '%locale%' }
    secret:          '%kernel.secret%'
    form: ~
    csrf_protection:
        enabled: true
    validation:
        enable_annotations: true
        cache: validator.mapping.cache.doctrine.apc
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~