hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookId
            strava: stravaId
            runkeeper: runkeeperId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook.app_id%
            client_secret:       %facebook.app_secret%
            scope:               email
            infos_url:           https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,gender
        strava:
            type:                strava
            client_id:           %strava.client_id%
            client_secret:       %strava.secret%
        runkeeper:
            type:                runkeeper
            client_id:           %runkeeper.client_id%
            client_secret:       %runkeeper.secret%
