liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        gallery_photo_thumb:
            quality: 60
            filters:
                thumbnail: { size: [400, 300], mode: inset }
        gallery_photo_standard:
            quality: 60
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
                watermark:
                    image: ../src/Caldera/Bundle/CriticalmassSiteBundle/Resources/public/images/watermark/criticalmass.png
                    size: 0.15
                    position: bottomright
        gallery_photo_large:
            quality: 60
            filters:
                thumbnail: { size: [2000, 2000], mode: inset }
                watermark:
                    image: ../src/Caldera/Bundle/CriticalmassSiteBundle/Resources/public/images/watermark/criticalmass.png
                    size: 0.15
                    position: bottomright
        city_image_wide:
            quality: 60
            filters:
                thumbnail: { size: [1140, 250], mode: inset }
        blog_featuredphoto_standard:
            quality: 80
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
        facebook_preview_image:
            quality: 60
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
        twitter_summary_large_image:
            quality: 50
            filters:
                thumbnail: { size: [800, 800], mode: inset }