twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
    date:
        timezone: Europe/Paris
        format: d.m.Y, H:i:s
        interval_format: '%%d days'