caldera_cycleways_incident_show:
    path:     /{slug}
    defaults: { _controller: AppBundle:Incident:show }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true

caldera_cycleways_incident_comment_add:
    path:     /{slug}/addcomment
    requirements:
        citySlug: '([a-zA-Z-]*)'
    defaults: { _controller: AppBundle:Post:write }

caldera_cycleways_incident_status_update:
    path:     /{slug}/update-status
    defaults: { _controller: AppBundle:IncidentStatus:update }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true

caldera_cycleways_incident_tag_update:
    path:     /{slug}/update-tag
    defaults: { _controller: AppBundle:Tag:update }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true

caldera_cycleways_incident_issuer_update:
    path:     /{slug}/update-issuer
    defaults: { _controller: AppBundle:Issuer:update }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true
