caldera_cycleways_incident_issuer_update:
    path:     /{slug}/update-issuer
    defaults: { _controller: AppBundle:Issuer:update }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true
