services:
    cycleways.timeline.cached:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\CachedTimeline
        arguments: [ '@doctrine', '@templating' ]
        calls:
            - [addCollector, ['@cycleways.timeline.collector.incident']]

    cycleways.timeline:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Timeline
        arguments: [ '@doctrine', '@templating' ]
        calls:
            - [addCollector, ['@cycleways.timeline.collector.incident']]

    cycleways.timeline.collector.incident:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Collector\IncidentCollector
        arguments: [ '@doctrine' ]
