services:
    cycleways.timeline.cached:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\CachedTimeline
        arguments: [ '@doctrine', '@templating' ]
        calls:
            - [addCollector, ['@cycleways.timeline.collector.incident']]

    cycleways.timeline:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Timeline
        arguments: [ '@doctrine', '@templating' ]
        calls:
            - [addCollector, ['@cycleways.timeline.collector.incident']]
            - [addCollector, ['@cycleways.timeline.collector.incident_photo']]
            - [addCollector, ['@cycleways.timeline.collector.incident_post']]

    cycleways.timeline.collector.incident:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Collector\IncidentCollector
        arguments: [ '@doctrine' ]

    cycleways.timeline.collector.incident_photo:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Collector\IncidentPhotoCollector
        arguments: [ '@doctrine' ]

    cycleways.timeline.collector.incident_post:
        class: Caldera\Bundle\CyclewaysBundle\Timeline\Collector\IncidentPostCollector
        arguments: [ '@doctrine' ]
