caldera_cycleways_api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix: /api

caldera_cycleways_internal:
    resource: "@AppBundle/Resources/config/routing/internal.yml"
    prefix: /internal

caldera_cycleways_search:
    resource: "@AppBundle/Resources/config/routing/search.yml"
    prefix: /

caldera_cycleways_photo:
    resource: "@AppBundle/Resources/config/routing/photo.yml"
    prefix: /

caldera_cycleways_incident:
    resource: "@AppBundle/Resources/config/routing/incident.yml"
    prefix: /

caldera_cycleways_list:
    resource: "@AppBundle/Resources/config/routing/list.yml"
    prefix: /

caldera_cycleways_map:
    resource: "@AppBundle/Resources/config/routing/map.yml"
    prefix: /

caldera_cycleways_city:
    resource: "@AppBundle/Resources/config/routing/city.yml"
    prefix: /
