caldera_cycleways_api:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/api.yml"
    prefix: /api

caldera_cycleways_internal:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/internal.yml"
    prefix: /internal

caldera_cycleways_search:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/search.yml"
    prefix: /

caldera_cycleways_incident:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/incident.yml"
    prefix: /

caldera_cycleways_city:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing/city.yml"
    prefix: /
