caldera_cycleways_frontpage:
    path:     /
    defaults: { _controller: CalderaCyclewaysBundle:Frontpage:index }

caldera_cycleways_incident_list_city:
    path:     /{citySlug}/list
    defaults: { _controller: CalderaCyclewaysBundle:Incident:list }

caldera_cycleways_incident_map_city:
    path:     /{citySlug}
    requirements:
        citySlug: '([a-zA-Z-]*)'
    defaults: { _controller: CalderaCyclewaysBundle:Incident:map }

caldera_cycleways_incident_add:
    path:     /{citySlug}/addincident
    requirements:
        citySlug: '([a-zA-Z-]*)'
    defaults: { _controller: CalderaCyclewaysBundle:Incident:add }