caldera_cycleways_incident_show:
    path:     /{slug}
    defaults: { _controller: CalderaCyclewaysBundle:Incident:show }
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    options:
        expose: true

caldera_cycleways_incident_comment_add:
    path:     /{slug}/addcomment
    requirements:
        citySlug: '([a-zA-Z-]*)'
    defaults: { _controller: CalderaCyclewaysBundle:Post:write }

caldera_cycleways_incident_photo_upload:
    path:     /{slug}/photoupload
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    defaults: { _controller: CalderaCyclewaysBundle:Photo:upload }

caldera_cycleways_incident_photo_show:
    path:     /{slug}/photo/{photoId}
    requirements:
        slug: '(.*)\-([0-9]{1,6})'
    defaults: { _controller: CalderaCyclewaysBundle:Photo:show }